ui:Set default value to timedelta arg in add_alarm()
Fixes #1338: Adding an alarm in ikhal causes a crash

> When adding an alarm in ikhal to an existing or new event the program
crashes.

> `TypeError: AlarmsEditor.add_alarm() missing 1 required positional argument: 'timedelta'`